// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	inventoryv1 "github.com/zhenklchhh/KozProject/shared/pkg/proto/inventory/v1"
	grpc "google.golang.org/grpc"
)

// InventoryServiceClient is an autogenerated mock type for the InventoryServiceClient type
type InventoryServiceClient struct {
	mock.Mock
}

type InventoryServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *InventoryServiceClient) EXPECT() *InventoryServiceClient_Expecter {
	return &InventoryServiceClient_Expecter{mock: &_m.Mock}
}

// GetPart provides a mock function with given fields: ctx, in, opts
func (_m *InventoryServiceClient) GetPart(ctx context.Context, in *inventoryv1.GetPartRequest, opts ...grpc.CallOption) (*inventoryv1.GetPartResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 *inventoryv1.GetPartResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *inventoryv1.GetPartRequest, ...grpc.CallOption) (*inventoryv1.GetPartResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *inventoryv1.GetPartRequest, ...grpc.CallOption) *inventoryv1.GetPartResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*inventoryv1.GetPartResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *inventoryv1.GetPartRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryServiceClient_GetPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPart'
type InventoryServiceClient_GetPart_Call struct {
	*mock.Call
}

// GetPart is a helper method to define mock.On call
//   - ctx context.Context
//   - in *inventoryv1.GetPartRequest
//   - opts ...grpc.CallOption
func (_e *InventoryServiceClient_Expecter) GetPart(ctx interface{}, in interface{}, opts ...interface{}) *InventoryServiceClient_GetPart_Call {
	return &InventoryServiceClient_GetPart_Call{Call: _e.mock.On("GetPart",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *InventoryServiceClient_GetPart_Call) Run(run func(ctx context.Context, in *inventoryv1.GetPartRequest, opts ...grpc.CallOption)) *InventoryServiceClient_GetPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*inventoryv1.GetPartRequest), variadicArgs...)
	})
	return _c
}

func (_c *InventoryServiceClient_GetPart_Call) Return(_a0 *inventoryv1.GetPartResponse, _a1 error) *InventoryServiceClient_GetPart_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryServiceClient_GetPart_Call) RunAndReturn(run func(context.Context, *inventoryv1.GetPartRequest, ...grpc.CallOption) (*inventoryv1.GetPartResponse, error)) *InventoryServiceClient_GetPart_Call {
	_c.Call.Return(run)
	return _c
}

// ListParts provides a mock function with given fields: ctx, in, opts
func (_m *InventoryServiceClient) ListParts(ctx context.Context, in *inventoryv1.ListPartsRequest, opts ...grpc.CallOption) (*inventoryv1.ListPartsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 *inventoryv1.ListPartsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *inventoryv1.ListPartsRequest, ...grpc.CallOption) (*inventoryv1.ListPartsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *inventoryv1.ListPartsRequest, ...grpc.CallOption) *inventoryv1.ListPartsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*inventoryv1.ListPartsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *inventoryv1.ListPartsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryServiceClient_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type InventoryServiceClient_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - in *inventoryv1.ListPartsRequest
//   - opts ...grpc.CallOption
func (_e *InventoryServiceClient_Expecter) ListParts(ctx interface{}, in interface{}, opts ...interface{}) *InventoryServiceClient_ListParts_Call {
	return &InventoryServiceClient_ListParts_Call{Call: _e.mock.On("ListParts",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *InventoryServiceClient_ListParts_Call) Run(run func(ctx context.Context, in *inventoryv1.ListPartsRequest, opts ...grpc.CallOption)) *InventoryServiceClient_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*inventoryv1.ListPartsRequest), variadicArgs...)
	})
	return _c
}

func (_c *InventoryServiceClient_ListParts_Call) Return(_a0 *inventoryv1.ListPartsResponse, _a1 error) *InventoryServiceClient_ListParts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryServiceClient_ListParts_Call) RunAndReturn(run func(context.Context, *inventoryv1.ListPartsRequest, ...grpc.CallOption) (*inventoryv1.ListPartsResponse, error)) *InventoryServiceClient_ListParts_Call {
	_c.Call.Return(run)
	return _c
}

// NewInventoryServiceClient creates a new instance of InventoryServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryServiceClient {
	mock := &InventoryServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
