with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
resolve-type-alias: False
issue-845-fix: True

packages:
  github.com/zhenklchhh/KozProject/o/internal/service:
    config:
      include-regex: ".*Service"

  github.com/zhenklchhh/KozProject/payment/internal/repository:
    config:
      include-regex: ".*Repository"

  github.com/zhenklchhh/KozProject/order/internal/service:
    config:
      include-regex: ".*Service"
  
  github.com/zhenklchhh/KozProject/order/internal/repository:
    config:
      include-regex: ".*Repository"

  github.com/jackc/pgx/v5:
    interfaces:
      Row:
        config:
          dir: "order/internal/repository/order/mocks" 
          outpkg: "mocks"

  github.com/zhenklchhh/KozProject/order/internal/repository/order:
    interfaces:
      PgxPool:
  
  github.com/zhenklchhh/KozProject/inventory/internal/service:
    config:
      include-regex: ".*Service"
  
  github.com/zhenklchhh/KozProject/inventory/internal/repository:
    config:
      include-regex: ".*Repository"
  github.com/zhenklchhh/KozProject/shared/pkg/proto/inventory/v1:
    config:
      include-regex: ".*ServiceClient"
  github.com/zhenklchhh/KozProject/shared/pkg/proto/payment/v1:
    config:
      include-regex: ".*ServiceClient"