version: '3'

vars:
  GO_VERSION: '1.26.1'
  GOLANGCI_LINT_VERSION: 'v2.1.5'
  GCI_VERSION: 'v0.13.6'
  GOFUMPT_VERSION: 'v0.8.0'
  BUF_VERSION: '1.53.0'
  PROTOC_GEN_GO_VERSION: 'v1.36.6'
  PROTOC_GEN_GO_GRPC_VERSION: 'v1.5.1'
  PROTOC_GEN_GRPC_GATEWAY_VERSION: 'v2.28.0'
  PROTOC_GEN_OPENAPIV2_VERSION: 'v2.28.0'
  OGEN_VERSION: 'v1.10.0'
  YQ_VERSION: 'v4.45.2'
  GRPCURL_VERSION: 'v1.9.3'
  MOCKERY_VERSION: 'v2.53.3'

  BIN_DIR: "{{.ROOT_DIR}}/bin"
  EXT: '{{if eq OS "windows"}}.exe{{end}}'
  GOLANGCI_LINT: "{{.BIN_DIR}}/golangci-lint{{.EXT}}"
  GCI: '{{.BIN_DIR}}/gci.exe'
  GOFUMPT: '{{.BIN_DIR}}/gofumpt.exe'
  BUF: '{{.BIN_DIR}}/buf.exe'
  OGEN: '{{.BIN_DIR}}/ogen.exe'
  YQ: '{{.BIN_DIR}}/yq.exe'
  PROTOC_GEN_GO: '{{.BIN_DIR}}/protoc-gen-go.exe'
  PROTOC_GEN_GO_GRPC: '{{.BIN_DIR}}/protoc-gen-go-grpc.exe'
  PROTOC_GEN_GRPC_GATEWAY: '{{.BIN_DIR}}/protoc-gen-go-grpc-gateway.exe'
  PROTOC_GEN_OPENAPIV2: '{{.BIN_DIR}}/protoc-gen-go-grpc-openapiv2.exe'
  GRPCURL: '{{.BIN_DIR}}/grpcurl.exe'
  JQ: '{{.BIN_DIR}}/gojq.exe'
  CURL: 'curl'
  MOCKERY: '{{.BIN_DIR}}/mockery'
  COVERAGE_DIR: '{{.ROOT_DIR | toSlash}}/coverage'
  COVERAGE_FILE: total.out

  NODE_MODULES_DIR: '{{.ROOT_DIR | toSlash}}/node_modules/.bin'
  REDOCLY: '{{.NODE_MODULES_DIR}}/redocly'

  OPEN_API_ORDER_V1_BASE: '{{.ROOT_DIR | toSlash}}/shared/api/order/v1/order.openapi.yaml'
  OPEN_API_ORDER_V1_BUNDLE: '{{.ROOT_DIR | toSlash}}/shared/api/bundles/order.openapi.v1.bundle.yaml'

  OPEN_API_FILES: '{{.ROOT_DIR | toSlash}}/shared/api/bundles'

  MODULES: inventory order payment

tasks:
  install-formatters:
    desc: "Устанавливает форматтеры gci и gofumpt в ./bin"
    cmds:
      - |
        [ -f {{.GOFUMPT}} ] || {
          echo '📦 Устанавливаем gofumpt {{.GOFUMPT_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install mvdan.cc/gofumpt@{{.GOFUMPT_VERSION}}
        }
        [ -f {{.GCI}} ] || {
          echo '📦 Устанавливаем gci {{.GCI_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install github.com/daixiang0/gci@{{.GCI_VERSION}}
        }
    status:
      - test -x {{.GOFUMPT}}
      - test -x {{.GCI}}

  test:
    desc: "Запускает юнит-тесты для всех модулей"
    summary: |
      Запускает юнит-тесты для указанных модулей проекта.
      Можно указать конкретные модули через переменную MODULES.
    cmds:
      - |
        ERR=0
        for mod in {{.MODULES}}; do
          if [ -d "$mod" ]; then
            echo "🧪 Тестируем модуль $mod"
            go test -v ./$mod/... || ERR=1
          fi
        done
        exit $ERR


  format:
    desc: "Форматирует весь проект gofumpt + gci, исключая mocks"
    deps: [install-formatters]
    cmds:
      - |
        echo "🧼 Форматируем через gofumpt ..."
        for module in {{.MODULES}}; do
          if [ -d "$module" ]; then
            echo "🧼 Форматируем $module"
            {{.GOFUMPT}} -extra -w $module
          fi
        done
      - |
        echo "🎯 Сортируем импорты через gci ..."
        for module in {{.MODULES}}; do
          if [ -d "$module" ]; then
            echo "🎯 Сортируем импорты в $module"
            {{.GCI}} write -s standard -s default -s "prefix(github.com/zhenklchhh/KozProject)" $module
          fi
        done

  install-golangci-lint:
    desc: "Устанавливает golangci-lint в каталог bin"
    cmds:
      - |
        [ -f {{.GOLANGCI_LINT}} ] || {
          mkdir -p {{.BIN_DIR}}
          echo "📦 Устанавливаем golangci-lint {{.GOLANGCI_LINT_VERSION}}..."
          GOBIN={{.BIN_DIR}} go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
        }
    status:
      - test -x {{.GOLANGCI_LINT}}

  lint:
    desc: "Запускает golangci-lint для всех модулей"
    deps: [install-golangci-lint]
    cmds:
      - |
        set -e
        ERR=0
        echo "🔍 Линтим все модули ..."
        for mod in {{.MODULES}}; do
          if [ -d "$mod" ]; then
            echo "🔍 Линтим $mod module"
            {{.GOLANGCI_LINT}} run $mod/... --config=$mod/.golangci.yml || ERR=1
          fi
        done
        exit $ERR

  install-buf:
    desc: "Устанавливает Buf в каталог bin"
    status:
      - test -f {{.BUF}}
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - echo "📦 Устанавливаем buf v{{.BUF_VERSION}}..."
      - GOBIN={{.BIN_DIR}} go install github.com/bufbuild/buf/cmd/buf@v{{.BUF_VERSION}}

  proto:install-plugins:
    desc: "Устанавливает protoc плагины в каталог bin"
    cmds:
      - |
        [ -f {{.PROTOC_GEN_GO}} ] || {
          echo '📦 Installing protoc-gen-go...'
          GOBIN={{.BIN_DIR}} go install google.golang.org/protobuf/cmd/protoc-gen-go@{{.PROTOC_GEN_GO_VERSION}}
        }
        [ -f {{.PROTOC_GEN_GO_GRPC}} ] || {
          echo '📦 Installing protoc-gen-go-grpc...'
          GOBIN={{.BIN_DIR}} go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@{{.PROTOC_GEN_GO_GRPC_VERSION}}
        }
        [ -f {{.PROTOC_GEN_GRPC_GATEWAY}} ] || {
          echo '📦 Installing protoc-gen-go-grpc-gateway...'
          GOBIN={{.BIN_DIR}} go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@{{.PROTOC_GEN_GRPC_GATEWAY_VERSION}}
        }
         [ -f {{.PROTOC_GEN_OPENAPIV2}} ] || {
          echo '📦 Installing protoc-gen-openapiv2...'
          GOBIN={{.BIN_DIR}} go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@{{.PROTOC_GEN_OPENAPIV2_VERSION}}
        }

  proto:install-deps:
    desc: "Устанавливает зависимости для валидации protobuf"
    dir: shared
    cmds:
      - |
        echo '📦 Устанавливаем зависимости для buf.validate...'
        go get buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate
        echo '✅ Зависимости для валидации установлены'

  proto:setup:
    desc: "Полная настройка окружения для работы с protobuf (для новых разработчиков)"
    deps: [install-buf, proto:install-plugins]
    cmds:
      - task: proto:install-deps
      - |
        echo '📦 Обновляем buf зависимости...'
        cd shared/proto && {{.BUF}} dep update
        echo '✅ Окружение для protobuf настроено!'
  
  proto:update-deps:
    deps: [ install-buf ]
    desc: Обновляет зависимости protobuf из удаленных репозиториев (googleapis и т.д.)
    dir: proto
    cmds:
      - |
        echo "🔄 Обновляем зависимости buf..."
        {{.BUF}} dep update

  proto:gen:
    deps: [install-buf, proto:install-plugins, proto:lint]
    desc: Генерация Go-кода из .proto
    dir: shared/proto
    cmds:
      - '{{.BUF}} generate'

  proto:lint:
    deps: [install-buf, proto:install-plugins, proto:update-deps]
    desc: Проверка .proto-файлов на соответствие стилю
    dir: shared/proto
    cmds:
      - '{{.BUF}} lint'

  mockery:gen:
    desc: "Генерирует моки интерфейсов с помощью mockery"
    deps: [ mockery:install ]
    cmds:
      - |
        echo '🧪 Генерация моков...'
        {{.MOCKERY}}

  test-coverage:
    desc: "Тесты с покрытием бизнес-логики (service/repository), отчёт по каждому модулю + общий"
    cmds:
      - |
        echo "🧪 Запускаем расчёт покрытия..."
        rm -rf {{.COVERAGE_DIR}}
        mkdir -p {{.COVERAGE_DIR}}
        
        ERR=0
        for mod in {{.MODULES}}; do
          echo "📦 Обрабатываем модуль: $mod"
        
          TARGET_PKGS=$(go list ./$mod/... \
            | grep -E '/(internal/(service|repository|api))' \
            | grep -vE '/(mocks|testdata|pkg|proto|pb|cmd)' \
            | paste -sd "," -)
        
          if [ -z "$TARGET_PKGS" ]; then
            echo "⚠️  Нет подходящих пакетов в $mod"
            continue
          fi
        
          go test -coverpkg="$TARGET_PKGS" \
            -coverprofile={{.COVERAGE_DIR}}/$mod.out \
            -covermode=atomic \
            $(echo "$TARGET_PKGS" | tr "," " ") || ERR=1
        done
        
        if [ $ERR -ne 0 ]; then
          echo "❌ Ошибки во время тестов"
          exit $ERR
        fi
        
        echo
        echo "📊 Покрытие по каждому модулю:"
        for mod in {{.MODULES}}; do
          OUTFILE="{{.COVERAGE_DIR}}/$mod.out"
          if [ -f "$OUTFILE" ]; then
            printf " • %s: " "$mod"
            go tool cover -func="$OUTFILE" | tail -n1
          fi
        done
        
        echo
        echo "📦 Склеиваем все покрытия..."
        {
          echo "mode: atomic"
          find {{.COVERAGE_DIR}} -type f -name '*.out' ! -name '{{.COVERAGE_FILE}}' \
            -exec grep -h -v "^mode:" {} +
        } > {{.COVERAGE_DIR}}/{{.COVERAGE_FILE}}
        
        echo
        echo "🧾 Общее покрытие по всем модулям:"
        go tool cover -func={{.COVERAGE_DIR}}/{{.COVERAGE_FILE}} | tail -n1

  coverage:html:
    desc: "Генерирует HTML-отчёт покрытия и открывает его в браузере"
    deps: [ test-coverage ]
    cmds:
      - |
        OUTPUT={{.COVERAGE_DIR}}/coverage.html
        echo "🌐 Генерируем HTML-отчёт..."
        go tool cover -html={{.COVERAGE_DIR}}/{{.COVERAGE_FILE}} -o $OUTPUT

        echo "🚀 Открываем $OUTPUT"
        if command -v open &> /dev/null; then
          open $OUTPUT  # macOS
        elif command -v xdg-open &> /dev/null; then
          xdg-open $OUTPUT  # Linux
        else
          echo "📂 Отчёт сохранён в $OUTPUT (открой вручную)"
        fi

  mockery:install:
    desc: "Устанавливает mockery в ./bin"
    cmds:
      - |
        [ -f {{.MOCKERY}} ] || {
          echo '📦 Installing mockery...'
          GOBIN={{.BIN_DIR}} go install github.com/vektra/mockery/v2@{{.MOCKERY_VERSION}}
        }
    status:
      - test -x {{.MOCKERY}}

  redocly-cli:install:
    desc: Установить локально Redocly CLI
    cmds:
      - |
        [ -f {{.REDOCLY}} ] || {
          npm ci
        }

  redocly-cli:order-v1-bundle:
    desc: Собрать OpenAPI в один файл через локальный redocly
    deps: [redocly-cli:install]
    cmds:
      - '{{.REDOCLY}} bundle {{.OPEN_API_ORDER_V1_BASE}} -o {{.OPEN_API_ORDER_V1_BUNDLE}}'

  redocly-cli:bundle:
    desc: Собрать все схемы OpenAPI в общие файлы через локальный redocly
    deps: [redocly-cli:install]
    cmds:
      - task: redocly-cli:order-v1-bundle

  ogen:install:
    desc: "Скачивает ogen в папку bin"
    cmds:
      - |
        [ -f {{.OGEN}} ] || {
          mkdir -p {{.BIN_DIR}}
          GOBIN={{.BIN_DIR}} go install github.com/ogen-go/ogen/cmd/ogen@{{.OGEN_VERSION}}
        }

  ogen:gen:
    desc: "Генерация Go-кода"
    deps: [ogen:install, yq:install]
    cmds:
      - task: redocly-cli:bundle
      - |
        for file in "{{.OPEN_API_FILES}}"/*.yaml "{{.OPEN_API_FILES}}"/*.yml; do
          if [ -f "$file" ]; then
            if grep -q "x-ogen" "$file"; then
              echo "🚀 Generating from: $file"
              TARGET=$("{{.YQ}}" e '."x-ogen".target' "$file")
              PACKAGE=$("{{.YQ}}" e '."x-ogen".package' "$file")
              if [ -z "$TARGET" ] || [ "$TARGET" = "null" ]; then
                echo "⚠️ Skip $file: 'x-ogen.target' not found"
                continue
              fi
              echo "📁 Target: $TARGET"
              echo "📦 Package: $PACKAGE"
              "{{.OGEN}}" --target "$TARGET" --package "$PACKAGE" --clean "$file" || exit 1
            fi
          fi
        done

  gen:
    desc: "Генерация всех proto и OpenAPI деклараций"
    cmds:
      - task: proto:gen
      - task: ogen:gen

  deps:update:
    desc: "Обновление зависимостей в go.mod во всех модулях"
    cmds:
      - |
        echo "🔄 Обновление зависимостей в go.mod во всех модулях"
        for mod in {{.MODULES}}; do
          if [ -d "$mod" ]; then
            echo "🔄 Обновление зависимостей в $mod"
            (cd "$mod" && go mod tidy -compat=1.24) || exit 1
          fi
        done

  yq:install:
    desc: "Устанавливает yq в bin/ при необходимости"
    cmds:
      - |
        [ -f {{.YQ}} ] || {
          echo '📦 Installing yq...'
          GOBIN={{.BIN_DIR}} go install github.com/mikefarah/yq/v4@{{.YQ_VERSION}}
        }

  grpcurl:install:
    desc: "Устанавливает grpcurl"
    status:
      - test -f {{.GRPCURL}}
    cmds:
      - GOBIN={{.BIN_DIR}} go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest

  jq:install:
    desc: "Устанавливает gojq (реализация jq на Go)"
    status:
      - test -f {{.JQ}}
    cmds:
      - GOBIN={{.BIN_DIR}} go install github.com/itchyny/gojq/cmd/gojq@latest