// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	paymentv1 "github.com/zhenklchhh/KozProject/shared/pkg/proto/payment/v1"
	grpc "google.golang.org/grpc"
)

// PaymentServiceClient is an autogenerated mock type for the PaymentServiceClient type
type PaymentServiceClient struct {
	mock.Mock
}

type PaymentServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentServiceClient) EXPECT() *PaymentServiceClient_Expecter {
	return &PaymentServiceClient_Expecter{mock: &_m.Mock}
}

// PayOrder provides a mock function with given fields: ctx, in, opts
func (_m *PaymentServiceClient) PayOrder(ctx context.Context, in *paymentv1.PayOrderRequest, opts ...grpc.CallOption) (*paymentv1.PayOrderResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 *paymentv1.PayOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *paymentv1.PayOrderRequest, ...grpc.CallOption) (*paymentv1.PayOrderResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *paymentv1.PayOrderRequest, ...grpc.CallOption) *paymentv1.PayOrderResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paymentv1.PayOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *paymentv1.PayOrderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PaymentServiceClient_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type PaymentServiceClient_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - in *paymentv1.PayOrderRequest
//   - opts ...grpc.CallOption
func (_e *PaymentServiceClient_Expecter) PayOrder(ctx interface{}, in interface{}, opts ...interface{}) *PaymentServiceClient_PayOrder_Call {
	return &PaymentServiceClient_PayOrder_Call{Call: _e.mock.On("PayOrder",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *PaymentServiceClient_PayOrder_Call) Run(run func(ctx context.Context, in *paymentv1.PayOrderRequest, opts ...grpc.CallOption)) *PaymentServiceClient_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*paymentv1.PayOrderRequest), variadicArgs...)
	})
	return _c
}

func (_c *PaymentServiceClient_PayOrder_Call) Return(_a0 *paymentv1.PayOrderResponse, _a1 error) *PaymentServiceClient_PayOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PaymentServiceClient_PayOrder_Call) RunAndReturn(run func(context.Context, *paymentv1.PayOrderRequest, ...grpc.CallOption) (*paymentv1.PayOrderResponse, error)) *PaymentServiceClient_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewPaymentServiceClient creates a new instance of PaymentServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentServiceClient {
	mock := &PaymentServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
