// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	pgx "github.com/jackc/pgx/v5"
	pgconn "github.com/jackc/pgx/v5/pgconn"
	mock "github.com/stretchr/testify/mock"
)

// PgxPool is an autogenerated mock type for the PgxPool type
type PgxPool struct {
	mock.Mock
}

type PgxPool_Expecter struct {
	mock *mock.Mock
}

func (_m *PgxPool) EXPECT() *PgxPool_Expecter {
	return &PgxPool_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, sql, args
func (_m *PgxPool) Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, sql)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 pgconn.CommandTag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) (pgconn.CommandTag, error)); ok {
		return rf(ctx, sql, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) pgconn.CommandTag); ok {
		r0 = rf(ctx, sql, args...)
	} else {
		r0 = ret.Get(0).(pgconn.CommandTag)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = rf(ctx, sql, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PgxPool_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type PgxPool_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...any
func (_e *PgxPool_Expecter) Exec(ctx interface{}, sql interface{}, args ...interface{}) *PgxPool_Exec_Call {
	return &PgxPool_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{ctx, sql}, args...)...)}
}

func (_c *PgxPool_Exec_Call) Run(run func(ctx context.Context, sql string, args ...any)) *PgxPool_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *PgxPool_Exec_Call) Return(_a0 pgconn.CommandTag, _a1 error) *PgxPool_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PgxPool_Exec_Call) RunAndReturn(run func(context.Context, string, ...any) (pgconn.CommandTag, error)) *PgxPool_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: ctx, sql, args
func (_m *PgxPool) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, sql)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 pgx.Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) (pgx.Rows, error)); ok {
		return rf(ctx, sql, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) pgx.Rows); ok {
		r0 = rf(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = rf(ctx, sql, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PgxPool_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type PgxPool_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...any
func (_e *PgxPool_Expecter) Query(ctx interface{}, sql interface{}, args ...interface{}) *PgxPool_Query_Call {
	return &PgxPool_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{ctx, sql}, args...)...)}
}

func (_c *PgxPool_Query_Call) Run(run func(ctx context.Context, sql string, args ...any)) *PgxPool_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *PgxPool_Query_Call) Return(_a0 pgx.Rows, _a1 error) *PgxPool_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PgxPool_Query_Call) RunAndReturn(run func(context.Context, string, ...any) (pgx.Rows, error)) *PgxPool_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function with given fields: ctx, sql, args
func (_m *PgxPool) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	var _ca []interface{}
	_ca = append(_ca, ctx, sql)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 pgx.Row
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) pgx.Row); ok {
		r0 = rf(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Row)
		}
	}

	return r0
}

// PgxPool_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type PgxPool_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...any
func (_e *PgxPool_Expecter) QueryRow(ctx interface{}, sql interface{}, args ...interface{}) *PgxPool_QueryRow_Call {
	return &PgxPool_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]interface{}{ctx, sql}, args...)...)}
}

func (_c *PgxPool_QueryRow_Call) Run(run func(ctx context.Context, sql string, args ...any)) *PgxPool_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *PgxPool_QueryRow_Call) Return(_a0 pgx.Row) *PgxPool_QueryRow_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PgxPool_QueryRow_Call) RunAndReturn(run func(context.Context, string, ...any) pgx.Row) *PgxPool_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}

// NewPgxPool creates a new instance of PgxPool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPgxPool(t interface {
	mock.TestingT
	Cleanup(func())
}) *PgxPool {
	mock := &PgxPool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
