name: Run Unit Tests

on:
  workflow_call:
    inputs:
      modules:
        required: true
        type: string
      go-version:
        required: true
        type: string

jobs:
  test:
    name: Run go test
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v4.2.2

      - name: 🛠 Set up Go
        uses: actions/setup-go@v5.4.0
        with:
          go-version-file: '.go-version'
          cache: false

      - name: 📌 Install Task
        uses: arduino/setup-task@v2.0.0

      - name: 🧪 Run unit tests via Taskfile
        env:
          MODULES: ${{ inputs.modules }}
        run: task test
